name: Bot3
on:
  push:
    branches:
      - stag2

env:
  TZ: America/Recife
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 525600

    steps:
      - name: Checkouts
        uses: actions/checkout@master
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Reclaiming disk space on / by disabling swap partition
        run: |
          sudo swapoff -av
          sudo rm -f /swapfile

      - name: Create swap (Avoid mk2fs issues)
        run: |
          sudo dd if=/dev/zero of=swap bs=4k count=1048576
          sudo mkswap swap
          sudo swapon swap

      - name: Setup git Environment
        run: |
          git config --global user.name "Velosh"
          git config --global user.email "daffetyxd@gmail.com"
          git config --global pull.rebase false

      - name: Setup Bobot Environment
        continue-on-error: true
        run: |
          git clone https://github.com/TrebleExperience/Bot3 Bot3
          mkdir configs && cd configs
          touch configs.prop
          echo "bot-token=${{ secrets.GH_2 }}" >> configs.prop
          echo "bot-username=xdskybot" >> configs.prop
          echo "bot-master=1072790346" >> configs.prop
          echo "publicChannel=TrebleExperience" >> configs.prop
          echo "bot-sf-pass=${{ secrets.PASS_SF }}" >> sf-creds.prop
          echo "bot-sf-proj=trebleexperience" >> sf-creds.prop
          echo "bot-sf-user=velosh" >> sf-creds.prop
          echo "bot-announcement-id=-1001489409825" >> sf-creds.prop
          echo "bot-sf-host=frs.sourceforge.net" >> sf-creds.prop
          echo "bot-send-announcement=true" >> sf-creds.prop
          echo '["1195724888","1484670029","1628025516","1469015383","1263663104"]' >> configs/allowed2port.json

      - name: Clone workflow
        continue-on-error: true
        run: |
          mkdir tmp && cd tmp
          git clone https://github.com/VeloshGSIs/Bot3-Workflow Bobot -b stag2

      - name: Install tools/packages
        continue-on-error: true
        timeout-minutes: 5
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache expect aria2 unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract file-roller device-tree-compiler liblzma-dev brotli liblz4-tool axel gawk aria2 detox cpio rename build-essential simg2img aria2 python3-pip

      - name: Setup Erfan GSIs Tool
        continue-on-error: true
        timeout-minutes: 2
        run: |
          git clone --recurse-submodules --depth 1 https://${TOKEN}@github.com/TrebleExperience/ErfanGSIs-TrebleExperience.git ErfanGSIs
          pip3 install wheel setuptools
          pip3 install backports.lzma docopt zstandard bsdiff4 protobuf pycrypto
          sudo pip3 install --upgrade protobuf

      - name: Install & Fix Java 16
        continue-on-error: true
        run: |
          sudo mkdir -p /usr/java/oracle
          cd /usr/java/oracle
          wget 'https://github.com/VeloshGSIs/Bot3-Workflow/releases/download/J16/jdk-16.0.1_linux-x64_bin.tar.gz' -O java.tar.gz; sudo tar -xzvf java.tar.gz
          JAVA_HOME=/usr/java/oracle/jdk-16.0.1
          PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
          export JAVA_HOME
          export PATH
          sudo update-alternatives --install "/usr/bin/java" "java" "/usr/java/oracle/jdk-16.0.1/bin/java" 1
          sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/java/oracle/jdk-16.0.1/bin/javac" 1
          echo '1' | sudo update-alternatives --config java
          echo '1' | sudo update-alternatives --config javac
          sudo dpkg --purge --force-depends ca-certificates-java
          sudo apt-get install ca-certificates-java -y

      - name: Build & Run Bot3 source
        continue-on-error: true
        timeout-minutes: 350
        run: |
          sed -i "s/'!'/'.'/g" Bot3/src/main/java/com/vegazsdev/bobobot/TelegramBot.java
          sed -i "s/'!'/'.'/g" Bot3/src/main/java/com/vegazsdev/bobobot/Main.java
          cd Bot3
          ./gradlew shadowJar
          cd ../; mv Bot3/build/libs/*.jar BoboBot.jar
          rm -rf Bot3
          sudo java -jar BoboBot.jar

      - name: Re-run Bot3 workflow
        continue-on-error: true
        timeout-minutes: 5
        run: |
          cd tmp/Bobot
          git commit --allow-empty -s -m "[LOOP] Re-run Bot3 workflow"
          expect -c "
          spawn git push -f
          expect \"Username\"
          send \"Velosh\r\"
          expect \"Password\"
          send \"${{ secrets.PASSWORD }}\r\"
          expect \"master -> master\"
          set timeout -10
          interact"
